# Generated by Django 5.2.13 on 2026-05-04 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "race_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("race_name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "races",
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_ref_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(max_length=255)),
                ("affiliation", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=32)),
                ("bio", models.TextField(blank=True)),
                ("manifesto_url", models.URLField(blank=True)),
                ("photo_initials", models.CharField(blank=True, max_length=4)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="voting.race",
                    ),
                ),
            ],
            options={
                "db_table": "candidates",
                "unique_together": {("race", "candidate_ref_id")},
            },
        ),
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("auec_admin", "AUEC Admin")],
                        default="student",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "eligible_races",
                    models.ManyToManyField(
                        blank=True, related_name="eligible_voters", to="voting.race"
                    ),
                ),
                (
                    "has_voted_races",
                    models.ManyToManyField(
                        blank=True, related_name="completed_voters", to="voting.race"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "voters",
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("hash_chain", models.CharField(max_length=64)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="voting.candidate",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="votes",
                        to="voting.race",
                    ),
                ),
            ],
            options={
                "db_table": "votes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("token_hash", "race"), name="unique_vote_per_token_race"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VotingToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("used", models.BooleanField(default=False)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tokens",
                        to="voting.race",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        blank=True,
                        db_column="voter_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voting_tokens",
                        to="voting.voter",
                    ),
                ),
            ],
            options={
                "db_table": "voting_tokens",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("used", False)),
                        fields=("voter", "race"),
                        name="unique_active_token_per_voter_race",
                    )
                ],
            },
        ),
    ]
