# Generated by Django 5.2.13 on 2026-05-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vote",
            name="unique_vote_per_token_race",
        ),
        migrations.AddField(
            model_name="candidate",
            name="is_nota",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="race",
            name="max_votes",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="race",
            name="nota_ref_id",
            field=models.IntegerField(default=999),
        ),
        migrations.AddField(
            model_name="vote",
            name="is_nota",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="votingtoken",
            name="ballot_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="vote",
            constraint=models.UniqueConstraint(
                fields=("token_hash", "candidate"),
                name="unique_vote_per_token_candidate",
            ),
        ),
    ]
